name: Comprehensive Issue Analysis

# Trigger when we want to analyze an issue and all its connected PRs
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to analyze'
        required: true
        type: string
      add_labels_to_prs:
        description: 'Also add priority labels to individual PRs'
        required: false
        type: boolean
        default: true
  
  # Or trigger automatically when an issue is closed
  issues:
    types: [closed]
    
  # Or trigger when a PR is opened that references an issue
  pull_request:
    types: [opened]

jobs:
  analyze-issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: 🎯 Analyze Issue and Connected PRs
        run: |
          # Use input issue number, closed issue number, or extract from PR
          ISSUE_NUMBER="${{ github.event.inputs.issue_number || github.event.issue.number }}"
          ADD_LABELS_TO_PRS="${{ github.event.inputs.add_labels_to_prs || 'true' }}"
          
          # If triggered by PR, try to extract issue number from PR title/body
          if [ -z "$ISSUE_NUMBER" ] && [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_TITLE="${{ github.event.pull_request.title }}"
            PR_BODY="${{ github.event.pull_request.body }}"
            
            # Extract issue number from PR title or body (basic regex)
            ISSUE_NUMBER=$(echo "$PR_TITLE $PR_BODY" | grep -oE '#[0-9]+' | head -1 | sed 's/#//')
            
            if [ -z "$ISSUE_NUMBER" ]; then
              echo "⚠️ No issue number found in PR title or body. Skipping analysis."
              exit 0
            fi
          fi
          
          echo "🚀 Starting comprehensive analysis for issue #$ISSUE_NUMBER"
          echo "🏷️ Add labels to PRs: $ADD_LABELS_TO_PRS"
          
          # Convert boolean string to JSON boolean
          if [ "$ADD_LABELS_TO_PRS" = "true" ]; then
            LABELS_JSON="true"
          else
            LABELS_JSON="false"
          fi
          
          curl -X POST "https://pullquestgithubbackend.onrender.com/api/github/analyze-issue" \
            -H "Content-Type: application/json" \
            -d "{
              \"owner\": \"${{ github.repository_owner }}\",
              \"repo\": \"${{ github.event.repository.name }}\",
              \"issueNumber\": $ISSUE_NUMBER,
              \"openaiApiKey\": \"pullquesttestzx7tehs\",
              \"addLabelsToPRs\": $LABELS_JSON
            }"
            
      - name: 📋 Analysis Complete
        run: |
          echo "✅ Issue analysis completed for #${{ github.event.inputs.issue_number || github.event.issue.number }}"
          echo "🏷️ Labels have been automatically applied based on AI analysis"
          echo "🎯 Priority labels assigned based on AI scoring"
